name: ML_Ops
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # core ML
  - click
  - python-dotenv>=0.5.1
  - pandas
  - numpy
  - nltk
  - scikit-learn
  - imbalanced-learn
  - xgboost
  - lightgbm
  - joblib
  - pyyaml
  - matplotlib
  - mlflow=2
  - boto3
  - dvc
  - dvc-s3

  # serving
  - fastapi>=0.115,<0.116
  - starlette>=0.40,<0.47
  - uvicorn
  - pydantic

  # development and documentation
  - sphinx
  - coverage
  - flake8
  - pytest
  - httpx>=0.27,<0.29

  # local package
  - pip:
      - -e .
