apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.enabled: "true"
  admin.password: '$2b$10$GD5jhRGk.ZBeEGKlrRVUyOFnhIJnJX81IHOsPffiSnfMaSrp5qtpG'
  admin.passwordMtime: "2026-06-30T00:00:00Z"
