apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-team

resources:
  - configmap.yml
  - minio.yml
  - mlflow.yml
  - webapp.yml
  - ml-team-project.yml
  - ml-team-application.yml