name: Legacy CI

on:
  workflow_dispatch:

jobs:
  notice:
    name: Use CI/CD workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print notice
        run: echo "The required CI/CD pipeline is defined in .github/workflows/ci-cd.yml."
